"""
Script à lancer UNE SEULE FOIS sur PythonAnywhere pour :
1. Renommer les 54 étudiants existants avec des noms complets (Nom Postnom Prénom) et les classer en L1
2. Ajouter 46 nouveaux étudiants en L1 (total L1 = 100)
3. Ajouter les étudiants de L2, L3 et M1 avec leurs départements (CEE / SI / PE)

Utilisation :
    python3 seed_students_v2.py
"""
import sqlite3
import os
from werkzeug.security import generate_password_hash

DB_PATH = os.path.join(os.path.dirname(__file__), "unilu.db")
DEMO_PASSWORD = "etudiant123"

# Noms complets pour renommer les 54 étudiants existants (par ordre d'ID croissant)
RENAMED_EXISTING = [
    "Mukendi Kalombo David",
    "Kazembe Tshiswaka Rachel",
    "Katanga Tshibuabua Elie",
    "Mwamba Mwenze Bienvenu",
    "Banza Mwamba Guy",
    "Kabasele Tshiswaka Deborah",
    "Nsimba Mwamba Belinda",
    "Mbayo Kanyinda Serge",
    "Lukusa Kalunga Sifa",
    "Muteba Mbombo Blaise",
    "Kabeya Kabuya Emmanuel",
    "Banza Kabeya Josué",
    "Tshimanga Kabuya Merveille",
    "Mukendi Kanku Emmanuel",
    "Mutombo Kabuya Prince",
    "Tshimanga Kanyinda Divine",
    "Lukusa Kanku Ruth",
    "Katanga Kabeya Grâce-Divin",
    "Mwepu Mwenze Freddy",
    "Mukendi Mulamba Bénie",
    "Mukendi Kalombo Bénie",
    "Lukusa Kanyinda Cédric",
    "Kabeya Tshisekedi Freddy",
    "Kayembe Mulumba Blaise",
    "Kabeya Tshibola Vanessa",
    "Nkulu Kayumba Patrick",
    "Kabongo Kabambi Grace",
    "Mputu Mwenze Chantal",
    "Kazembe Kalunga Aline",
    "Kabeya Kabambi Aline",
    "Mbayo Mwenze Rodrigue",
    "Kazembe Mulumba Junior",
    "Lukusa Kanku Christian",
    "Mutombo Tshiama Elie",
    "Kasongo Tshiala Josée",
    "Kalenga Tshiala Esther",
    "Kabongo Kanku Fifi",
    "Nsimba Kabamba Serge",
    "Kalubi Kalunga Naomie",
    "Ilunga Mbombo Aline",
    "Kabwe Kalasa Bijoux",
    "Mutombo Kayumba Sarah",
    "Nkulu Kabeya Emmanuel",
    "Mbuyi Mwamba Christian",
    "Ngoy Kabongo Rachel",
    "Kabongo Kabanga Fifi",
    "Kazadi Kabuya Grace",
    "Nkulu Mbombo Sarah",
    "Kasongo Kabamba Deborah",
    "Kazadi Kabambi Emmanuel",
    "Kalonji Tshinyama Josée",
    "Mwepu Kalala Divine",
    "Kabongo Kabeya Jean-Paul",
    "Ilunga Mulamba Sifa",
]

# (matricule, nom complet, niveau, département, montant_du)
NEW_STUDENTS = [
    ("UNILU-CRIM-L1-001", "Kalenga Tshilumba Rebecca", "L1", None, 150),
    ("UNILU-CRIM-L1-002", "Ilunga Mwenze Josué", "L1", None, 150),
    ("UNILU-CRIM-L1-003", "Ntumba Mulamba Divin", "L1", None, 150),
    ("UNILU-CRIM-L1-004", "Kabongo Mulumba Dieudonné", "L1", None, 150),
    ("UNILU-CRIM-L1-005", "Ilunga Kanyinda Bijoux", "L1", None, 150),
    ("UNILU-CRIM-L1-006", "Kabongo Mwenze Espérance", "L1", None, 150),
    ("UNILU-CRIM-L1-007", "Kabeya Tshiama Moïse", "L1", None, 150),
    ("UNILU-CRIM-L1-008", "Kalonji Mulamba Blaise", "L1", None, 150),
    ("UNILU-CRIM-L1-009", "Kabeya Tshiala Josué", "L1", None, 150),
    ("UNILU-CRIM-L1-010", "Ngoy Kabuya Jean-Paul", "L1", None, 150),
    ("UNILU-CRIM-L1-011", "Kalonji Kabanga Josué", "L1", None, 150),
    ("UNILU-CRIM-L1-012", "Mutombo Mulamba Rodrigue", "L1", None, 150),
    ("UNILU-CRIM-L1-013", "Ntumba Kabambi Josué", "L1", None, 150),
    ("UNILU-CRIM-L1-014", "Kalonji Tshiala Elie", "L1", None, 150),
    ("UNILU-CRIM-L1-015", "Banza Kabongo Josué", "L1", None, 150),
    ("UNILU-CRIM-L1-016", "Mwepu Mwanza Nadège", "L1", None, 150),
    ("UNILU-CRIM-L1-017", "Ntumba Kabanga Chantal", "L1", None, 150),
    ("UNILU-CRIM-L1-018", "Tshibangu Tshibuabua Bienvenu", "L1", None, 150),
    ("UNILU-CRIM-L1-019", "Kalonji Kabanga Franck", "L1", None, 150),
    ("UNILU-CRIM-L1-020", "Mputu Mwanza Fifi", "L1", None, 150),
    ("UNILU-CRIM-L1-021", "Ngoy Kanku Bijoux", "L1", None, 150),
    ("UNILU-CRIM-L1-022", "Muteba Kabuya Cédric", "L1", None, 150),
    ("UNILU-CRIM-L1-023", "Kalenga Kabeya Clarisse", "L1", None, 150),
    ("UNILU-CRIM-L1-024", "Kabongo Kabongo Bijoux", "L1", None, 150),
    ("UNILU-CRIM-L1-025", "Kayembe Mwamba Josée", "L1", None, 150),
    ("UNILU-CRIM-L1-026", "Kalonji Kayumba Nadège", "L1", None, 150),
    ("UNILU-CRIM-L1-027", "Nsimba Mulumba Christian", "L1", None, 150),
    ("UNILU-CRIM-L1-028", "Tshibangu Kabongo Bijoux", "L1", None, 150),
    ("UNILU-CRIM-L1-029", "Katanga Mwamba Freddy", "L1", None, 150),
    ("UNILU-CRIM-L1-030", "Ngoy Mwamba Sarah", "L1", None, 150),
    ("UNILU-CRIM-L1-031", "Mwamba Mwadi Josée", "L1", None, 150),
    ("UNILU-CRIM-L1-032", "Mbayo Kabambi Prince", "L1", None, 150),
    ("UNILU-CRIM-L1-033", "Kasongo Tshibuabua Freddy", "L1", None, 150),
    ("UNILU-CRIM-L1-034", "Katanga Kanyinda Blaise", "L1", None, 150),
    ("UNILU-CRIM-L1-035", "Kazembe Kalobo Clarisse", "L1", None, 150),
    ("UNILU-CRIM-L1-036", "Tshimanga Mwadi Blaise", "L1", None, 150),
    ("UNILU-CRIM-L1-037", "Mputu Tshisekedi Deborah", "L1", None, 150),
    ("UNILU-CRIM-L1-038", "Tshibangu Kabuya Josée", "L1", None, 150),
    ("UNILU-CRIM-L1-039", "Kabeya Tshisekedi Bijoux", "L1", None, 150),
    ("UNILU-CRIM-L1-040", "Kalenga Kanyinda Samuel", "L1", None, 150),
    ("UNILU-CRIM-L1-041", "Mwamba Kalasa Rodrigue", "L1", None, 150),
    ("UNILU-CRIM-L1-042", "Mukendi Kabanga Trésor", "L1", None, 150),
    ("UNILU-CRIM-L1-043", "Kazadi Kabeya Junior", "L1", None, 150),
    ("UNILU-CRIM-L1-044", "Kalenga Mwamba Vanessa", "L1", None, 150),
    ("UNILU-CRIM-L1-045", "Lukusa Tshinyama Grâce-Divin", "L1", None, 150),
    ("UNILU-CRIM-L1-046", "Mbuyi Tshilumba Sarah", "L1", None, 150),
    ("UNILU-CRIM-L2-CEE-001", "Banza Tshiama Blaise", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-002", "Kasongo Mulumba Fiston", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-003", "Tshimanga Kabambi Prisca", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-004", "Mutombo Kabamba Rodrigue", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-005", "Kabwe Kabambi Junior", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-006", "Ilunga Kalobo Fiston", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-007", "Kalenga Tshiama Bénie", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-008", "Mbayo Kalunga Clarisse", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-009", "Mutombo Kalobo Prince", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-010", "Banza Kalasa Rachel", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-011", "Kalenga Kabambi Israël", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-012", "Katanga Tshiswaka Clarisse", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-013", "Muteba Kabamba Fiston", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-014", "Kalenga Mwamba Judith", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-015", "Mwepu Tshibola Freddy", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-016", "Tshibangu Kalobo Christian", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-017", "Kazembe Kalala Josée", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-018", "Kabwe Kabeya Grâce-Divin", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-019", "Nkulu Kanyinda Sifa", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-020", "Kabasele Kanyinda Blaise", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-021", "Kasongo Tshibola Prince", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-022", "Katanga Kabamba Grace", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-023", "Banza Tshiswaka Esther", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-024", "Lukusa Kayumba Fifi", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-025", "Ntumba Mulumba Chantal", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-026", "Kabeya Kalasa Fiston", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-027", "Kasongo Kalasa Sifa", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-028", "Banza Kabeya Moïse", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-029", "Kabasele Tshiama Bijoux", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-030", "Kazembe Tshilumba David", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-031", "Banza Tshinyama Cédric", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-032", "Kabasele Tshiama Prisca", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-033", "Kabasele Kalombo Blaise", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-034", "Mbuyi Kalombo Bijoux", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-CEE-035", "Tshimanga Tshisekedi Trésor", "L2", "CEE", 150),
    ("UNILU-CRIM-L2-SI-001", "Kalonji Tshinyama Guy", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-002", "Mbayo Mwenze Elie", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-003", "Kalubi Kabeya Josée", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-004", "Kabwe Kabeya Jean-Paul", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-005", "Mwamba Kayumba Israël", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-006", "Muteba Kalombo Jean-Paul", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-007", "Kalombo Mbombo Esther", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-008", "Mukendi Mbombo Freddy", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-009", "Mwepu Mulamba Serge", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-010", "Kabwe Kabuya Divine", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-011", "Kazembe Kalombo Junior", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-012", "Kalubi Mulamba Vanessa", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-013", "Nsimba Kabeya Vanessa", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-014", "Kabwe Tshisekedi Franck", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-015", "Kalombo Mwadi Grâce-Divin", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-016", "Mbayo Kabamba Grâce-Divin", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-017", "Tshimanga Tshisekedi Prince", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-018", "Kabwe Tshiala Serge", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-019", "Kabasele Tshibuabua Merveille", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-020", "Kabeya Mbombo Christian", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-021", "Mwepu Kabambi Franck", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-022", "Kabwe Kabamba Belinda", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-023", "Lukusa Mwanza Elie", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-024", "Tshibangu Tshiswaka Guy", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-025", "Muteba Kanyinda Marie-Jeanne", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-026", "Kazembe Kabeya Esther", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-027", "Kalenga Kabuya Merveille", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-028", "Lukusa Mwanza Bijoux", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-029", "Kazadi Mulumba Fiston", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-030", "Kabasele Kabambi Belinda", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-031", "Tshibangu Tshiama Samuel", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-032", "Kalenga Tshiswaka Divine", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-033", "Kabeya Kalombo Merveille", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-034", "Mputu Kalasa Naomie", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-035", "Tshimanga Mwamba Dieudonné", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-036", "Kayembe Kabuya Esther", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-037", "Kayembe Mulumba Fifi", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-038", "Mwamba Mwanza Judith", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-039", "Lukusa Mwamba Grace", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-040", "Kayembe Tshibola Sifa", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-041", "Muteba Mulumba Merveille", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-042", "Mputu Kabambi Emmanuel", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-043", "Mukendi Tshiala Belinda", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-044", "Mukendi Tshibuabua Jean-Paul", "L2", "SI", 150),
    ("UNILU-CRIM-L2-SI-045", "Kalombo Kabeya Ruth", "L2", "SI", 150),
    ("UNILU-CRIM-L3-CEE-001", "Mbuyi Tshisekedi Judith", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-002", "Tshibangu Mwanza Bijoux", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-003", "Kabongo Kayumba Marie-Jeanne", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-004", "Kazadi Tshinyama Emmanuel", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-005", "Mwamba Tshiama Bijoux", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-006", "Ilunga Kanku Chantal", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-007", "Mukendi Kalobo Patrick", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-008", "Kazembe Kabeya Bénie", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-009", "Kabongo Tshibola David", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-010", "Mutombo Kalala Christian", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-011", "Tshimanga Mbombo Freddy", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-012", "Muteba Tshibuabua Esther", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-013", "Lukusa Tshibola Ruth", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-014", "Mukendi Kalunga Trésor", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-015", "Kabongo Kabamba Grace", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-016", "Muteba Kalasa Bienvenu", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-017", "Mutombo Kabongo Rebecca", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-018", "Kalubi Kalasa Judith", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-019", "Muteba Kabanga Marie-Jeanne", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-020", "Kabeya Mwanza Fiston", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-021", "Mbuyi Kalunga Divin", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-022", "Mwamba Mulumba Moïse", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-023", "Kazadi Kalala Aline", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-024", "Kalubi Mwenze Blaise", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-025", "Mbayo Kanyinda Marie-Jeanne", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-026", "Kabongo Mwadi Naomie", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-027", "Mukendi Mwadi Trésor", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-028", "Ntumba Mwanza Judith", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-029", "Kabeya Tshiala Rachel", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-CEE-030", "Ntumba Kalala Trésor", "L3", "CEE", 150),
    ("UNILU-CRIM-L3-SI-001", "Mbuyi Mulumba Clarisse", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-002", "Muteba Tshiama Esther", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-003", "Muteba Tshibuabua Trésor", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-004", "Mukendi Mwenze Emmanuel", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-005", "Mbuyi Mulamba Divin", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-006", "Mwamba Kabanga Rachel", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-007", "Ilunga Mulamba Franck", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-008", "Kalubi Tshinyama David", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-009", "Mwepu Mwanza Fifi", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-010", "Kalenga Kabanga Fifi", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-011", "Kabongo Mwenze David", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-012", "Katanga Mwamba Vanessa", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-013", "Kazembe Tshibola Grâce-Divin", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-014", "Nsimba Kabongo Rodrigue", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-015", "Ilunga Kabamba Divin", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-016", "Nkulu Kalunga Patrick", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-017", "Nsimba Mwadi Judith", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-018", "Nkulu Kabamba Moïse", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-019", "Banza Tshiswaka Trésor", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-020", "Kabasele Mulumba Fifi", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-021", "Kalubi Tshibola Emmanuel", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-022", "Mukendi Kayumba Bijoux", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-023", "Kabeya Kalombo Belinda", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-024", "Kabeya Kalombo Moïse", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-025", "Banza Kalobo Sarah", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-026", "Banza Kabeya Samuel", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-027", "Mwepu Tshiala Sifa", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-028", "Ilunga Kanku Jean-Paul", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-029", "Mukendi Tshiama Fifi", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-030", "Mbayo Mulamba Divine", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-031", "Banza Tshiala Prince", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-032", "Kalubi Kabambi Marie-Jeanne", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-033", "Kalubi Kalasa Freddy", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-034", "Lukusa Mwadi Nadège", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-035", "Mputu Kabeya Fiston", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-036", "Ilunga Kabeya Clarisse", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-037", "Ngoy Mwadi Emmanuel", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-038", "Mukendi Tshilumba Esther", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-039", "Ilunga Mulamba Emmanuel", "L3", "SI", 150),
    ("UNILU-CRIM-L3-SI-040", "Katanga Tshibola Christian", "L3", "SI", 150),
    ("UNILU-CRIM-M1-CEE-001", "Kalenga Kanku Rebecca", "M1", "CEE", 150),
    ("UNILU-CRIM-M1-CEE-002", "Mputu Kabambi Marie-Jeanne", "M1", "CEE", 150),
    ("UNILU-CRIM-M1-CEE-003", "Kabeya Kalasa Clarisse", "M1", "CEE", 150),
    ("UNILU-CRIM-M1-CEE-004", "Mwamba Kalala Grace", "M1", "CEE", 150),
    ("UNILU-CRIM-M1-CEE-005", "Kalubi Mwadi Sarah", "M1", "CEE", 150),
    ("UNILU-CRIM-M1-CEE-006", "Katanga Tshisekedi Deborah", "M1", "CEE", 150),
    ("UNILU-CRIM-M1-CEE-007", "Mbuyi Mwanza Merveille", "M1", "CEE", 150),
    ("UNILU-CRIM-M1-CEE-008", "Mwamba Mwanza Belinda", "M1", "CEE", 150),
    ("UNILU-CRIM-M1-CEE-009", "Nsimba Tshilumba Merveille", "M1", "CEE", 150),
    ("UNILU-CRIM-M1-CEE-010", "Tshibangu Kabamba Israël", "M1", "CEE", 150),
    ("UNILU-CRIM-M1-CEE-011", "Mukendi Kalunga Bijoux", "M1", "CEE", 150),
    ("UNILU-CRIM-M1-CEE-012", "Mbuyi Kalobo Espérance", "M1", "CEE", 150),
    ("UNILU-CRIM-M1-CEE-013", "Ntumba Kabeya Dieudonné", "M1", "CEE", 150),
    ("UNILU-CRIM-M1-CEE-014", "Kalombo Tshiala Bénie", "M1", "CEE", 150),
    ("UNILU-CRIM-M1-CEE-015", "Kabongo Mwenze Samuel", "M1", "CEE", 150),
    ("UNILU-CRIM-M1-SI-001", "Nkulu Kabeya Divine", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-002", "Mukendi Kabuya Franck", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-003", "Kasongo Tshibuabua Josée", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-004", "Mputu Kabamba Belinda", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-005", "Kazembe Tshinyama Judith", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-006", "Katanga Mulumba Divin", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-007", "Lukusa Kanku Belinda", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-008", "Nkulu Kalobo Freddy", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-009", "Kabongo Kabeya Judith", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-010", "Tshimanga Kalasa Dieudonné", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-011", "Ngoy Kabanga Bénie", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-012", "Mbuyi Tshiama Chantal", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-013", "Banza Kabeya Ruth", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-014", "Mutombo Kalala Rebecca", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-015", "Ilunga Mbombo Franck", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-016", "Kabwe Kanyinda Nadège", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-017", "Mwepu Mwadi Deborah", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-018", "Kabwe Mbombo Bienvenu", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-019", "Tshimanga Mwanza Josué", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-020", "Kayembe Kanyinda Junior", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-021", "Kabasele Mulamba Esther", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-022", "Katanga Kalobo Dieudonné", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-023", "Kazadi Kalombo Vanessa", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-024", "Mbuyi Tshiswaka Serge", "M1", "SI", 150),
    ("UNILU-CRIM-M1-SI-025", "Banza Tshiswaka Rodrigue", "M1", "SI", 150),
    ("UNILU-CRIM-M1-PE-001", "Kalenga Kabongo Vanessa", "M1", "PE", 150),
    ("UNILU-CRIM-M1-PE-002", "Ilunga Tshiswaka Bienvenu", "M1", "PE", 150),
    ("UNILU-CRIM-M1-PE-003", "Mbuyi Tshiama Nadège", "M1", "PE", 150),
    ("UNILU-CRIM-M1-PE-004", "Ngoy Kalobo Grace", "M1", "PE", 150),
    ("UNILU-CRIM-M1-PE-005", "Kabongo Kabuya David", "M1", "PE", 150),
    ("UNILU-CRIM-M1-PE-006", "Kalonji Kalasa Grace", "M1", "PE", 150),
    ("UNILU-CRIM-M1-PE-007", "Mbuyi Kabeya Franck", "M1", "PE", 150),
    ("UNILU-CRIM-M1-PE-008", "Lukusa Kanyinda Merveille", "M1", "PE", 150),
    ("UNILU-CRIM-M1-PE-009", "Kalenga Tshisekedi Franck", "M1", "PE", 150),
    ("UNILU-CRIM-M1-PE-010", "Nsimba Kalombo David", "M1", "PE", 150),
    ("UNILU-CRIM-M1-PE-011", "Ilunga Kabeya Belinda", "M1", "PE", 150),
    ("UNILU-CRIM-M1-PE-012", "Mwamba Kayumba Jean-Paul", "M1", "PE", 150),
    ("UNILU-CRIM-M1-PE-013", "Kalonji Kabeya Divin", "M1", "PE", 150),
    ("UNILU-CRIM-M1-PE-014", "Tshibangu Tshibuabua Merveille", "M1", "PE", 150),
    ("UNILU-CRIM-M1-PE-015", "Ilunga Kabanga Franck", "M1", "PE", 150),
    ("UNILU-CRIM-M2-CEE-001", "Mbuyi Tshiswaka Bienvenu", "M2", "CEE", 150),
    ("UNILU-CRIM-M2-CEE-002", "Mwamba Kabeya Freddy", "M2", "CEE", 150),
    ("UNILU-CRIM-M2-CEE-003", "Mukendi Mwanza Rebecca", "M2", "CEE", 150),
    ("UNILU-CRIM-M2-CEE-004", "Banza Tshibola Bienvenu", "M2", "CEE", 150),
    ("UNILU-CRIM-M2-CEE-005", "Mwamba Kabuya David", "M2", "CEE", 150),
    ("UNILU-CRIM-M2-CEE-006", "Kabongo Kabamba Esther", "M2", "CEE", 150),
    ("UNILU-CRIM-M2-CEE-007", "Mputu Kabongo Rebecca", "M2", "CEE", 150),
    ("UNILU-CRIM-M2-CEE-008", "Ilunga Tshiswaka Chantal", "M2", "CEE", 150),
    ("UNILU-CRIM-M2-CEE-009", "Kazembe Kalunga Chantal", "M2", "CEE", 150),
    ("UNILU-CRIM-M2-CEE-010", "Kabongo Mwamba Prisca", "M2", "CEE", 150),
    ("UNILU-CRIM-M2-CEE-011", "Ntumba Kabongo Sarah", "M2", "CEE", 150),
    ("UNILU-CRIM-M2-CEE-012", "Mwamba Kayumba Freddy", "M2", "CEE", 150),
    ("UNILU-CRIM-M2-CEE-013", "Kasongo Kalasa Fiston", "M2", "CEE", 150),
    ("UNILU-CRIM-M2-SI-001", "Mwepu Mwenze Esther", "M2", "SI", 150),
    ("UNILU-CRIM-M2-SI-002", "Lukusa Kanyinda Christian", "M2", "SI", 150),
    ("UNILU-CRIM-M2-SI-003", "Mutombo Kanku Clarisse", "M2", "SI", 150),
    ("UNILU-CRIM-M2-SI-004", "Mputu Kanyinda Prince", "M2", "SI", 150),
    ("UNILU-CRIM-M2-SI-005", "Kazembe Kabongo Aline", "M2", "SI", 150),
    ("UNILU-CRIM-M2-SI-006", "Kazembe Tshilumba Divin", "M2", "SI", 150),
    ("UNILU-CRIM-M2-SI-007", "Mwamba Kanku Jean-Paul", "M2", "SI", 150),
    ("UNILU-CRIM-M2-SI-008", "Kabongo Mwamba Aline", "M2", "SI", 150),
    ("UNILU-CRIM-M2-SI-009", "Mbuyi Mwadi David", "M2", "SI", 150),
    ("UNILU-CRIM-M2-SI-010", "Katanga Kabambi Bijoux", "M2", "SI", 150),
    ("UNILU-CRIM-M2-SI-011", "Kayembe Mbombo Cédric", "M2", "SI", 150),
    ("UNILU-CRIM-M2-SI-012", "Kabongo Kabanga Ruth", "M2", "SI", 150),
    ("UNILU-CRIM-M2-SI-013", "Nsimba Kalunga Prisca", "M2", "SI", 150),
    ("UNILU-CRIM-M2-PE-001", "Tshimanga Kabambi Grace", "M2", "PE", 150),
    ("UNILU-CRIM-M2-PE-002", "Mukendi Mulumba Junior", "M2", "PE", 150),
    ("UNILU-CRIM-M2-PE-003", "Mputu Kabambi Judith", "M2", "PE", 150),
    ("UNILU-CRIM-M2-PE-004", "Mbuyi Kalunga Grâce-Divin", "M2", "PE", 150),
    ("UNILU-CRIM-M2-PE-005", "Nsimba Kayumba Deborah", "M2", "PE", 150),
    ("UNILU-CRIM-M2-PE-006", "Kabongo Mwamba Prince", "M2", "PE", 150),
    ("UNILU-CRIM-M2-PE-007", "Ntumba Kabeya Guy", "M2", "PE", 150),
    ("UNILU-CRIM-M2-PE-008", "Kayembe Kalunga Israël", "M2", "PE", 150),
    ("UNILU-CRIM-M2-PE-009", "Mwamba Tshiama Deborah", "M2", "PE", 150),
    ("UNILU-CRIM-M2-PE-010", "Kabasele Tshiama Grâce-Divin", "M2", "PE", 150),
    ("UNILU-CRIM-M2-PE-011", "Kabongo Tshilumba Aline", "M2", "PE", 150),
    ("UNILU-CRIM-M2-PE-012", "Ilunga Kayumba Aline", "M2", "PE", 150),
    ("UNILU-CRIM-M2-PE-013", "Kasongo Kalombo Bijoux", "M2", "PE", 150),
    ("UNILU-CRIM-M2-PE-014", "Ntumba Tshiswaka Prisca", "M2", "PE", 150),
]


def migrate_columns(cur):
    for statement in [
        "ALTER TABLE students ADD COLUMN department TEXT",
        "ALTER TABLE students ADD COLUMN payment_currency TEXT",
        "ALTER TABLE students ADD COLUMN amount_local_paid INTEGER",
    ]:
        try:
            cur.execute(statement)
        except sqlite3.OperationalError:
            pass  # colonne déjà présente


def main():
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    migrate_columns(cur)
    conn.commit()

    # 1. Renommer et reclasser en L1 les étudiants existants (par ordre d'id)
    existing_ids = [row[0] for row in cur.execute("SELECT id FROM students ORDER BY id").fetchall()]
    renamed_count = 0
    for idx, student_id in enumerate(existing_ids):
        if idx < len(RENAMED_EXISTING):
            cur.execute(
                "UPDATE students SET name = ?, level = ?, department = NULL WHERE id = ?",
                (RENAMED_EXISTING[idx], "L1", student_id),
            )
            renamed_count += 1
    conn.commit()

    # 2. Insérer les nouveaux étudiants (L1 restants, L2, L3, M1)
    added = 0
    skipped = 0
    for matricule, name, level, dept, amount_due in NEW_STUDENTS:
        existing = cur.execute(
            "SELECT id FROM students WHERE UPPER(matricule) = UPPER(?)", (matricule,)
        ).fetchone()
        if existing:
            skipped += 1
            continue
        cur.execute("""
            INSERT INTO students (matricule, password_hash, name, faculty, level, department, amount_due, paid)
            VALUES (?, ?, ?, ?, ?, ?, ?, 0)
        """, (
            matricule,
            generate_password_hash(DEMO_PASSWORD),
            name,
            "Faculté de Criminologie",
            level,
            dept,
            amount_due,
        ))
        added += 1

    conn.commit()
    conn.close()

    print(f"Étudiants existants renommés/reclassés en L1 : {renamed_count}")
    print(f"Nouveaux étudiants ajoutés : {added}")
    print(f"Déjà existants (ignorés) : {skipped}")
    print(f"Mot de passe pour tous les nouveaux comptes : {DEMO_PASSWORD}")


if __name__ == "__main__":
    main()